services:
  # app:
  #   build: .
  #   container_name: transactions_app
  #   volumes:
  #     - .:/go/src/
  #   ports:
  #     - 3150:8000
  #   depends_on:
  #     - db
  #   extra_hosts:
  #     - "host.docker.internal:172.17.0.1"
  #   # networks:
  #   #   - cred_system_network

  db:
    build: .docker/postgres
    container_name: postgres_interview_payments_db
    restart: unless-stopped
    tty: true
    ports:
      - 3200:5432
    volumes:
      - .docker/postgres/dbdata-payment:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=payment
      - POSTGRES_PASSWORD=thisislocal-noneedtoworry
    extra_hosts:
      - "host.docker.internal:172.17.0.1"


networks:
  cred_system_network:
    driver: bridge
