// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: authorizeMessage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthorizationServiceClient is the client API for AuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizationServiceClient interface {
	Process(ctx context.Context, in *AuthorizationProcessRequest, opts ...grpc.CallOption) (*AuthorizationProcessResponse, error)
	ReprocessPendingAuthorization(ctx context.Context, in *AuthorizationReprocessPendingRequest, opts ...grpc.CallOption) (*AuthorizationReprocessPendingResponse, error)
}

type authorizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationServiceClient(cc grpc.ClientConnInterface) AuthorizationServiceClient {
	return &authorizationServiceClient{cc}
}

func (c *authorizationServiceClient) Process(ctx context.Context, in *AuthorizationProcessRequest, opts ...grpc.CallOption) (*AuthorizationProcessResponse, error) {
	out := new(AuthorizationProcessResponse)
	err := c.cc.Invoke(ctx, "/authorization.AuthorizationService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) ReprocessPendingAuthorization(ctx context.Context, in *AuthorizationReprocessPendingRequest, opts ...grpc.CallOption) (*AuthorizationReprocessPendingResponse, error) {
	out := new(AuthorizationReprocessPendingResponse)
	err := c.cc.Invoke(ctx, "/authorization.AuthorizationService/ReprocessPendingAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServiceServer is the server API for AuthorizationService service.
// All implementations must embed UnimplementedAuthorizationServiceServer
// for forward compatibility
type AuthorizationServiceServer interface {
	Process(context.Context, *AuthorizationProcessRequest) (*AuthorizationProcessResponse, error)
	ReprocessPendingAuthorization(context.Context, *AuthorizationReprocessPendingRequest) (*AuthorizationReprocessPendingResponse, error)
	mustEmbedUnimplementedAuthorizationServiceServer()
}

// UnimplementedAuthorizationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorizationServiceServer struct {
}

func (UnimplementedAuthorizationServiceServer) Process(context.Context, *AuthorizationProcessRequest) (*AuthorizationProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedAuthorizationServiceServer) ReprocessPendingAuthorization(context.Context, *AuthorizationReprocessPendingRequest) (*AuthorizationReprocessPendingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReprocessPendingAuthorization not implemented")
}
func (UnimplementedAuthorizationServiceServer) mustEmbedUnimplementedAuthorizationServiceServer() {}

// UnsafeAuthorizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationServiceServer will
// result in compilation errors.
type UnsafeAuthorizationServiceServer interface {
	mustEmbedUnimplementedAuthorizationServiceServer()
}

func RegisterAuthorizationServiceServer(s grpc.ServiceRegistrar, srv AuthorizationServiceServer) {
	s.RegisterService(&AuthorizationService_ServiceDesc, srv)
}

func _AuthorizationService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.AuthorizationService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).Process(ctx, req.(*AuthorizationProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_ReprocessPendingAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationReprocessPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).ReprocessPendingAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.AuthorizationService/ReprocessPendingAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).ReprocessPendingAuthorization(ctx, req.(*AuthorizationReprocessPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizationService_ServiceDesc is the grpc.ServiceDesc for AuthorizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authorization.AuthorizationService",
	HandlerType: (*AuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _AuthorizationService_Process_Handler,
		},
		{
			MethodName: "ReprocessPendingAuthorization",
			Handler:    _AuthorizationService_ReprocessPendingAuthorization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorizeMessage.proto",
}
